
class NotFoundError(Exception):
	pass

class DuplicateError(Exception):
	pass

